# Generated by AI (PR Orchestrator)
"""Offline contract tests. Git uses temporary local origins, never GitHub."""
import copy
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

import controller as c


def git(directory, *args):
    env = {k: v for k, v in os.environ.items()
           if not k.startswith("GIT_") and k not in ("GH_TOKEN", "GITHUB_TOKEN")}
    env.update(GIT_CONFIG_NOSYSTEM="1", GIT_CONFIG_GLOBAL=os.devnull,
               GIT_TERMINAL_PROMPT="0")
    return subprocess.check_output(
        ["git", "-c", "core.hooksPath=", "-c", "commit.gpgsign=false",
         "-c", "protocol.allow=never", "-c", "protocol.file.allow=always",
         "-C", str(directory), *args], env=env, stderr=subprocess.PIPE
    ).decode().strip()


class FakeGitHub:
    """Only the HTTP boundary is fake; all content proofs and pushes use real Git."""

    def __init__(self, origin, head, source, target, commits):
        self.origin = origin
        self.repo = {"id": 1369849596,
                     "full_name": "AleksanderGladkov/BCApps-Backport-Test"}
        self.source = {"number": 7, "merged": True, "merge_commit_sha": source,
                       "head": {"sha": head}, "changed_files": 1,
                       "base": {"ref": "main", "repo": self.repo}}
        self.commits = [{"sha": value} for value in commits]
        self.target = target
        self.actor = 59250993
        self.issues = []
        self.pulls = []
        self.comments = {}
        self.calls = []
        self.fail_post = None
        self.lose_post_response = None
        self.runs = []
        self.stale_paths = set()

    def workflow_run(self, run_id=123, source_pr=7, dry_run=False, attempt=1):
        return {"id": run_id, "workflow_id": 456, "run_attempt": attempt,
                "repository": copy.deepcopy(self.repo), "head_repository": copy.deepcopy(self.repo),
                "path": ".github/workflows/backport-demo.yml", "event": "workflow_dispatch",
                "head_branch": "main", "display_title": "Backport PR " + str(source_pr)
                + " to 29.x (dry run = " + str(dry_run).lower() + ")"}

    def request(self, method, path, data=None):
        self.calls.append((method, path, copy.deepcopy(data)))
        route, _, query = path.partition("?")
        root = "/repos/" + self.repo["full_name"]
        if method == "POST" and self.fail_post == route:
            raise c.Failure("api_write_ambiguous")
        if method == "GET":
            if route.startswith("/users/"):
                value = {"id": self.actor, "login": "AleksanderGladkov"}
            elif route == root:
                value = self.repo
            elif route.startswith(root + "/actions/runs/"):
                value = next(x for x in self.runs if x["id"] == int(route.split("/")[-1]))
            elif route == root + "/actions/workflows/backport-demo.yml/runs":
                from urllib.parse import parse_qs
                params = parse_qs(query)
                assert set(params) == {"per_page", "page"} and params["per_page"] == ["100"]
                page = int(params["page"][0])
                value = {"total_count": len(self.runs), "workflow_runs": self.runs[(page - 1) * 100:page * 100]}
            elif route == root + "/pulls/7":
                value = self.source
            elif route == root + "/pulls/7/commits":
                from urllib.parse import parse_qs
                page = int(parse_qs(query).get("page", ["1"])[0])
                value = self.commits[(page - 1) * 100:page * 100]
            elif route.startswith(root + "/branches/"):
                value = {"commit": {"sha": self.target}}
            elif route in (root + "/issues", root + "/pulls"):
                values = (self.issues + [{**obj, "pull_request": {"html_url": obj["html_url"]}}
                                        for obj in self.pulls]
                          if route.endswith("/issues") else self.pulls)
                from urllib.parse import parse_qs
                page = int(parse_qs(query).get("page", ["1"])[0])
                value = values[(page - 1) * 100:page * 100]
            elif route.endswith("/comments"):
                number = int(route.split("/")[-2])
                value = self.comments.get(number, [])
            elif "/issues/" in route:
                value = next(x for x in self.issues if x["number"] == int(route.split("/")[-1]))
            elif "/pulls/" in route:
                value = next(x for x in self.pulls if x["number"] == int(route.split("/")[-1]))
            else:
                raise AssertionError((method, path))
        elif method == "POST":
            if route == root + "/issues":
                value = {"number": 101, "id": 1001, "state": "open", **data,
                         "html_url": "https://github.com/" + self.repo["full_name"] + "/issues/101",
                         "user": {"id": 41898282}}
                self.issues.append(value)
            elif route == root + "/pulls":
                head = git(self.origin, "rev-parse", "refs/heads/" + data["head"])
                value = {"number": 102, "id": 1002, "state": "open", "merged": False,
                         "body": data["body"], "user": {"id": 41898282},
                         "head": {"sha": head, "ref": data["head"], "repo": self.repo},
                         "base": {"ref": data["base"], "repo": self.repo},
                         "html_url": "https://github.com/" + self.repo["full_name"] + "/pull/102"}
                self.pulls.append(value)
                git(self.origin, "update-ref", "refs/pull/102/head", head)
            elif route.endswith("/comments"):
                number = int(route.split("/")[-2])
                value = {"id": 2000 + number, "user": {"id": 41898282}, **data}
                self.comments.setdefault(number, []).append(value)
            else:
                raise AssertionError((method, path))
            if self.lose_post_response == route:
                raise c.Failure("api_write_ambiguous")
        elif method == "PATCH" and "/issues/comments/" in route:
            value = next(x for items in self.comments.values() for x in items
                         if x["id"] == int(route.split("/")[-1]))
            value.update(data)
        else:
            raise AssertionError((method, path))
        if method == "GET" and route in self.stale_paths:
            return []
        return copy.deepcopy(value)


class ExecutorTests(unittest.TestCase):
    def setUp(self):
        network = patch("urllib.request.OpenerDirector.open", side_effect=AssertionError("network forbidden"))
        network.start()
        self.addCleanup(network.stop)
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.origin = self.root / "origin"
        self.origin.mkdir()
        git(self.origin, "init", "-b", "main")
        git(self.origin, "config", "user.name", "Fixture")
        git(self.origin, "config", "user.email", "fixture@example.invalid")
        (self.origin / ".gitattributes").write_bytes(b"*.al text eol=lf\n")
        (self.origin / "src").mkdir()
        (self.origin / "src/one.al").write_bytes(b"one\ntwo\nthree\n")
        git(self.origin, "add", ".")
        git(self.origin, "commit", "-m", "base")
        self.target = self.base = git(self.origin, "rev-parse", "HEAD")
        git(self.origin, "branch", "releases/29.x")
        git(self.origin, "switch", "-c", "feature")
        (self.origin / "src/one.al").write_bytes(b"ONE\ntwo\nthree\n")
        git(self.origin, "commit", "-am", "feature")
        self.head = git(self.origin, "rev-parse", "HEAD")
        commits = git(self.origin, "rev-list", "--reverse", self.target + ".." + self.head).splitlines()
        git(self.origin, "update-ref", "refs/pull/7/head", self.head)
        git(self.origin, "switch", "main")
        git(self.origin, "merge", "--squash", "feature")
        git(self.origin, "commit", "-m", "squash")
        self.source = git(self.origin, "rev-parse", "HEAD")
        self.env = {
            "GITHUB_REPOSITORY": "AleksanderGladkov/BCApps-Backport-Test",
            "GITHUB_REPOSITORY_ID": "1369849596", "GITHUB_REF": "refs/heads/main",
            "GITHUB_ACTOR_ID": "59250993", "GITHUB_TRIGGERING_ACTOR": "AleksanderGladkov",
            "INPUT_SOURCE_PR": "7", "INPUT_DRY_RUN": "false",
            "GITHUB_RUN_ID": "123", "GITHUB_RUN_ATTEMPT": "1",
            "RUNNER_TEMP": str(self.root / "runner"), "GH_TOKEN": "offline-fixture",
        }
        self.api = FakeGitHub(self.origin, self.head, self.source, self.target, commits)
        self.configure()

    def configure(self):
        self.config = c.Config.from_env(self.env)
        current = self.api.workflow_run(int(self.config.run_id), self.config.source_pr,
                                        self.config.dry_run, int(self.config.run_attempt))
        for run in self.api.runs:
            if run["id"] == current["id"]:
                run.update(current)
                break
        else:
            self.api.runs.insert(0, current)
        self.executor = c.Controller(
            self.config, api=self.api,
            repo_factory=lambda cfg: c.GitRepo(cfg, origin=str(self.origin), allow_file=True))

    def fresh_attempt(self, run_id="123", attempt="2"):
        self.env.update(GITHUB_RUN_ID=run_id, GITHUB_RUN_ATTEMPT=attempt,
                        STATE_DIR=str(self.root / ("state-" + run_id + "-" + attempt)))
        self.configure()

    def stages(self, last="prepare"):
        for name in ("validate", "track", "prepare", "publish"):
            result = getattr(self.executor, name)()
            if name == last:
                return result

    def alter_json(self, name, edit):
        path = self.config.state_dir / name
        value = json.loads(path.read_text())
        edit(value)
        path.write_text(json.dumps(value))

    def multi_commit_source(self, integration, newline=b"\n"):
        """Build real PR commits with independent edits in the same file."""
        git(self.origin, "reset", "--hard", self.base)
        lines = ["line " + str(i) for i in range(20)]
        path = self.origin / "src/one.al"
        path.write_bytes(newline.join(x.encode() for x in lines) + newline)
        git(self.origin, "commit", "-am", "spaced base")
        self.target = git(self.origin, "rev-parse", "HEAD")
        git(self.origin, "branch", "-f", "releases/29.x", self.target)
        git(self.origin, "switch", "-C", "feature", self.target)
        lines[1] = "FIRST EDIT"
        path.write_bytes(newline.join(x.encode() for x in lines) + newline)
        git(self.origin, "commit", "-am", "first edit")
        lines[18] = "SECOND EDIT"
        path.write_bytes(newline.join(x.encode() for x in lines) + newline)
        git(self.origin, "commit", "-am", "second edit")
        git(self.origin, "switch", "main")
        if integration == "rebase":
            (self.origin / "unrelated.txt").write_bytes(b"main advanced\n")
            git(self.origin, "add", ".")
            git(self.origin, "commit", "-m", "advance main")
            git(self.origin, "switch", "feature")
            git(self.origin, "rebase", "main")
            git(self.origin, "switch", "main")
        self.head = git(self.origin, "rev-parse", "feature")
        base = git(self.origin, "merge-base", "main", "feature")
        commits = git(self.origin, "rev-list", "--reverse", base + ".." + self.head).splitlines()
        self.assertEqual(len(commits), 2)
        git(self.origin, "update-ref", "refs/pull/7/head", self.head)
        if integration in ("fast-forward", "rebase"):
            git(self.origin, "merge", "--ff-only", "feature")
        elif integration == "partial-parent":
            git(self.origin, "merge", "--ff-only", commits[0])
            git(self.origin, "merge", "--squash", "feature")
            git(self.origin, "commit", "-m", "alleged squash missing first edit")
        else:
            self.assertEqual(integration, "squash")
            git(self.origin, "merge", "--squash", "feature")
            git(self.origin, "commit", "-m", "complete squash")
        self.source = git(self.origin, "rev-parse", "HEAD")
        self.api = FakeGitHub(self.origin, self.head, self.source, self.target, commits)
        self.configure()
        return commits

    def assert_partial_source_rejected(self, integration):
        commits = self.multi_commit_source(integration)
        with self.executor.repo_factory(self.config) as repo:
            repo.fetch()
            parent = repo.text("rev-parse", self.source + "^")
            self.assertEqual(parent, commits[0])
            self.assertEqual(repo.text("merge-base", parent, self.head), parent)
            # Both old raw diffs match and changed_files=1, but only B is copied.
            self.assertEqual(repo.raw(parent, self.source), repo.raw(parent, self.head))
            files = c.parse_raw_diff(repo.raw(parent, self.source))
            self.assertEqual([x[0] for x in files], ["src/one.al"])
            self.assertEqual(self.api.source["changed_files"], 1)
            incomplete = repo.patch(parent, self.source)
            self.assertIn(b"+SECOND EDIT", incomplete)
            self.assertNotIn(b"+FIRST EDIT", incomplete)
        with self.assertRaisesRegex(c.Failure, "^source_not_squash$"):
            self.executor.validate()
        self.assertFalse((self.config.state_dir / "plan.json").exists())
        self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))

    def test_two_commit_fast_forward_cannot_drop_first_same_file_edit(self):
        self.assert_partial_source_rejected("fast-forward")

    def test_two_commit_rebase_cannot_drop_first_same_file_edit(self):
        self.assert_partial_source_rejected("rebase")

    def test_squash_parent_cannot_already_contain_a_pr_commit(self):
        self.assert_partial_source_rejected("partial-parent")
        self.assertNotIn(self.source, [x["sha"] for x in self.api.commits])

    def test_prove_plan_rejects_partial_source_using_exact_api_commits(self):
        commits = self.multi_commit_source("fast-forward")
        # A plan from the old validator must not bypass the repeated proof.
        plan = {**self.config.binding(), "source_sha": self.source,
                "source_head_sha": self.head, "target_base_sha": self.target,
                "target_ref": c.TARGET, "files": ["src/one.al"], "commits": commits}
        with self.executor.repo_factory(self.config) as repo:
            with self.assertRaisesRegex(c.Failure, "^source_not_squash$"):
                self.executor.prove_plan(repo, plan, self.api.source)

    def test_prove_plan_rejects_truncated_commit_list_before_git_proof(self):
        self.multi_commit_source("squash")
        plan = self.executor.validate()
        plan["commits"] = [self.head]
        with self.executor.repo_factory(self.config) as repo:
            with patch.object(repo, "prove", wraps=repo.prove) as prove:
                with self.assertRaisesRegex(c.Failure, "^source_commits_changed$"):
                    self.executor.prove_plan(repo, plan, self.api.source)
                prove.assert_not_called()

    def test_multi_commit_squash_copies_both_edits_with_lf_and_crlf(self):
        for newline in (b"\n", b"\r\n"):
            with self.subTest(newline=newline):
                commits = self.multi_commit_source("squash", newline)
                self.env.update(INPUT_DRY_RUN="true", STATE_DIR=str(self.root / ("state-" + newline.hex())))
                self.configure()
                with self.executor.repo_factory(self.config) as repo:
                    repo.fetch()
                    for commit in commits:
                        self.assertFalse(repo.ancestor(commit, self.source + "^"))
                    self.assertNotIn(b"\r", repo.run("show", self.source + ":src/one.al"))
                result = self.stages()
                self.assertEqual(result["status"], "applied")
                self.assertEqual(self.executor.read_plan()["commits"], commits)
                patch_bytes = (self.config.state_dir / "patch.bin").read_bytes()
                self.assertIn(b"+FIRST EDIT", patch_bytes)
                self.assertIn(b"+SECOND EDIT", patch_bytes)
                self.assertEqual(self.executor.publish()["status"], "dry-run")
                self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))

    def test_single_commit_source_equal_to_head_is_complete(self):
        git(self.origin, "reset", "--hard", self.head)
        self.api.source["merge_commit_sha"] = self.head
        self.assertEqual(self.stages()["status"], "applied")
        self.assertEqual(self.executor.read_plan()["commits"], [self.head])
        self.assertIn(b"+ONE", (self.config.state_dir / "patch.bin").read_bytes())

    def test_environment_is_strict_and_fork_owner_is_mandatory(self):
        for key, values in {
            "GITHUB_REPOSITORY": ["microsoft/BCApps", "evil/BCApps-Backport-Test"],
            "GITHUB_REPOSITORY_ID": ["1", ""], "GITHUB_REF": ["refs/heads/feature", ""],
            "GITHUB_ACTOR_ID": ["1234", "", "59250993\n"],
            "INPUT_SOURCE_PR": ["0", "-1", "2147483648", "7;echo", " 7", "7\n", "01"],
            "INPUT_DRY_RUN": ["True", "1", "", "false\n"],
            "GITHUB_RUN_ID": ["", "1\n"], "GITHUB_RUN_ATTEMPT": ["0"],
            "GITHUB_TRIGGERING_ACTOR": ["", "owner\n", "../owner"],
            "ALLOWED_ACTOR_IDS": ["", "owner", "59250993,", "1;evil"],
        }.items():
            for value in values:
                with self.subTest(key=key, value=value), self.assertRaises(c.Failure):
                    c.Config.from_env({**self.env, key: value})

    def test_rerun_triggering_actor_must_also_be_allowlisted(self):
        self.api.actor = 12
        with self.assertRaises(c.Failure):
            self.executor.validate()
        self.assertFalse(any(method != "GET" for method, _, _ in self.api.calls))

    def test_allowlist_comes_only_from_protected_variable(self):
        cfg = c.Config.from_env({**self.env, "GITHUB_ACTOR_ID": "12",
                                 "ALLOWED_ACTOR_IDS": "59250993,12"})
        self.assertIn(12, cfg.allowed_actor_ids)
        with self.assertRaises(c.Failure):
            c.Config.from_env({**self.env, "GITHUB_ACTOR_ID": "12",
                               "INPUT_ALLOWED_ACTOR_IDS": "12"})

    def test_source_repository_merge_base_and_metadata_are_checked(self):
        original = copy.deepcopy(self.api.source)
        mutations = [lambda x: x.update(merged=False),
                     lambda x: x.update(number=8),
                     lambda x: x["base"].update(ref="other"),
                     lambda x: x["base"]["repo"].update(id=1),
                     lambda x: x.update(merge_commit_sha="bad"),
                     lambda x: x.update(changed_files=2)]
        for change in mutations:
            with self.subTest(change=change), self.assertRaises(c.Failure):
                self.api.source = copy.deepcopy(original)
                change(self.api.source)
                self.executor.validate()

    def test_non_squash_net_diff_is_rejected(self):
        (self.origin / "src/one.al").write_text("unrelated\n")
        git(self.origin, "commit", "-am", "not the PR patch")
        self.api.source["merge_commit_sha"] = git(self.origin, "rev-parse", "HEAD")
        with self.assertRaises(c.Failure):
            self.executor.validate()

    def test_paths_reject_traversal_controls_backslashes_and_non_al(self):
        for path in ("src/../x.al", "/src/a.al", "src//a.al", "src/./a.al",
                     "src\\a.al", "src/a\nb.al", "src/a\x00.al", "src/a\x7f.al",
                     ".github/x.al", "src/a.py", "src/C:/a.al", "src/CON.al",
                     "src/a. /b.al", "src/.git/a.al"):
            with self.subTest(path=path), self.assertRaises(c.Failure):
                c.validate_path(path)
        self.assertEqual(c.validate_path("src/Module/My Code.al"), "src/Module/My Code.al")

    def test_raw_entries_reject_executable_symlink_gitlink_and_control_paths(self):
        oid = b"a" * 40
        for mode in (b"100755", b"120000", b"160000"):
            raw = b":100644 " + mode + b" " + oid + b" " + oid + b" M\0src/a.al\0"
            with self.subTest(mode=mode), self.assertRaises(c.Failure):
                c.parse_raw_diff(raw)
        with self.assertRaises(c.Failure):
            c.parse_raw_diff(b":100644 100644 " + oid + b" " + oid + b" M\0src/a\nb.al\0")

    def test_size_limits_and_binary_blobs_are_rejected(self):
        for contents in (b"a\0b", b"x" * (1024 * 1024 + 1)):
            with self.subTest(size=len(contents)):
                git(self.origin, "switch", "feature")
                (self.origin / "src/one.al").write_bytes(contents)
                git(self.origin, "commit", "-am", "large or binary")
                head = git(self.origin, "rev-parse", "HEAD")
                git(self.origin, "update-ref", "refs/pull/7/head", head)
                git(self.origin, "switch", "main")
                git(self.origin, "reset", "--hard", self.target)
                git(self.origin, "merge", "--squash", "feature")
                git(self.origin, "commit", "-m", "squash")
                self.api.source.update(merge_commit_sha=git(self.origin, "rev-parse", "HEAD"))
                self.api.source["head"]["sha"] = head
                self.api.commits = [{"sha": value} for value in git(
                    self.origin, "rev-list", "--reverse", self.target + ".." + head).splitlines()]
                with self.assertRaises(c.Failure):
                    self.executor.validate()

    def test_file_count_and_total_patch_limits(self):
        with patch.object(c, "MAX_FILES", 0), self.assertRaises(c.Failure):
            self.executor.validate()
        with patch.object(c, "MAX_PATCH", 10), self.assertRaises(c.Failure):
            self.executor.validate()

    def test_all_stages_dry_run_never_write_remotely(self):
        self.env["INPUT_DRY_RUN"] = "true"
        self.configure()
        result = self.stages("publish")
        self.assertEqual(result["status"], "dry-run")
        self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))
        self.assertEqual(git(self.origin, "branch", "--list", "backport/*"), "")

    def test_clean_cherry_pick_publish_and_duplicate_reconcile(self):
        result = self.stages()
        self.assertEqual(result["status"], "applied")
        self.assertFalse(result["published"])
        patch_bytes = (self.config.state_dir / "patch.bin").read_bytes()
        self.assertEqual(result["patch_sha256"], hashlib.sha256(patch_bytes).hexdigest())
        published = self.executor.publish()
        self.assertEqual(published["status"], "pr-created")
        self.assertEqual(published["pr_url"], self.api.pulls[0]["html_url"])
        self.assertEqual(self.executor.publish()["status"], "pr-reused")
        self.assertEqual(self.executor.track()["issue_number"], 101)
        self.assertEqual(len(self.api.issues), 1)
        self.assertEqual(len(self.api.pulls), 1)
        self.assertEqual([len(x) for x in self.api.comments.values()], [1, 1])
        branch = "refs/heads/backport/29.x/pr-7"
        self.assertEqual(git(self.origin, "show", branch + ":src/one.al").splitlines(), ["ONE", "two", "three"])
        self.assertEqual(git(self.origin, "rev-parse", branch + "^"), self.target)

    def test_full_rerun_after_publication_reuses_issue_and_pr(self):
        self.assertEqual(self.stages("publish")["status"], "pr-created")
        listed = self.executor.pages("/issues?state=all")
        self.assertEqual(len(listed), 2)
        self.assertEqual(sum("pull_request" in obj for obj in listed), 1)
        self.assertTrue(all(self.executor.marker(self.executor.read_plan()) in obj["body"] for obj in listed))
        head = git(self.origin, "rev-parse", "backport/29.x/pr-7")
        creates = sum(method == "POST" for method, _, _ in self.api.calls)
        for attempt in ("1", "2"):
            with self.subTest(attempt=attempt):
                self.env["GITHUB_RUN_ATTEMPT"] = attempt
                if attempt == "2":
                    # New jobs use fresh attempt-bound artifacts, not the old journal.
                    self.env["STATE_DIR"] = str(self.root / "attempt-2-state")
                self.configure()
                self.assertEqual(self.stages("publish")["status"], "pr-reused")
                self.assertEqual(self.executor.read_plan()["run_attempt"], attempt)
                self.assertEqual(len(self.api.issues), 1)
                self.assertEqual(len(self.api.pulls), 1)
                self.assertEqual(sum(method == "POST" for method, _, _ in self.api.calls), creates)
                self.assertEqual(git(self.origin, "rev-parse", "backport/29.x/pr-7"), head)
                self.assertEqual([len(x) for x in self.api.comments.values()], [1, 1])

    def test_conflict_emits_resolver_input_without_publication(self):
        git(self.origin, "switch", "releases/29.x")
        (self.origin / "src/one.al").write_text("RELEASE\ntwo\nthree\n")
        git(self.origin, "commit", "-am", "target edit")
        self.api.target = git(self.origin, "rev-parse", "HEAD")
        git(self.origin, "switch", "main")
        result = self.stages()
        self.assertEqual(result["status"], "needs-attention")
        conflict = json.loads((self.config.state_dir / "conflict.json").read_text())
        self.assertEqual(set(conflict), {"repo", "source_pr", "source_sha",
                                        "target_base_sha", "worktree", "files"})
        self.assertEqual(conflict["repo"], self.env["GITHUB_REPOSITORY"])
        self.assertEqual(conflict["files"][0]["relative_path"], "src/one.al")
        self.assertTrue(Path(conflict["files"][0]["absolute_path"]).is_absolute())
        self.assertTrue(Path(conflict["worktree"]).is_dir())
        self.assertEqual(self.executor.publish()["status"], "needs-attention")
        self.assertEqual(len(self.api.pulls), 0)
        self.assertEqual(git(self.origin, "branch", "--list", "backport/*"), "")

    def test_already_applied_requires_content_proof_and_creates_no_pr(self):
        git(self.origin, "switch", "releases/29.x")
        git(self.origin, "cherry-pick", self.source)
        self.api.target = git(self.origin, "rev-parse", "HEAD")
        git(self.origin, "switch", "main")
        self.assertEqual(self.stages()["status"], "already_applied")
        self.assertEqual(self.executor.publish()["status"], "already_applied")
        self.assertFalse(self.api.pulls)

    def test_artifacts_cannot_cross_runs_attempts_or_source_context(self):
        self.stages()
        for key, value in (("GITHUB_RUN_ID", "124"), ("GITHUB_RUN_ATTEMPT", "2"),
                           ("INPUT_SOURCE_PR", "8")):
            with self.subTest(key=key):
                env = self.env.copy()
                self.env[key] = value
                self.configure()
                with self.assertRaises(c.Failure):
                    self.executor.publish()
                self.env = env
        self.assertFalse(self.api.pulls)

    def test_result_and_patch_tampering_fail_closed(self):
        self.stages()
        original = (self.config.state_dir / "result.json").read_bytes()
        for change in (lambda x: x.update(tree_sha="a" * 40),
                       lambda x: x.update(status="resolved"),
                       lambda x: x.update(published=True),
                       lambda x: x.update(plan_hash="a" * 64),
                       lambda x: x.update(extra="untrusted")):
            with self.subTest(change=change), self.assertRaises(c.Failure):
                (self.config.state_dir / "result.json").write_bytes(original)
                self.alter_json("result.json", change)
                self.executor.publish()
        (self.config.state_dir / "result.json").write_bytes(original)
        (self.config.state_dir / "patch.bin").write_bytes(b"evil")
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.assertFalse(self.api.pulls)

    def test_target_advance_has_no_branch_or_pr_write(self):
        self.stages()
        self.api.target = "a" * 40
        self.assertEqual(self.executor.publish()["status"], "needs-attention")
        self.assertFalse(self.api.pulls)
        self.assertEqual(git(self.origin, "branch", "--list", "backport/*"), "")

    def test_source_or_triggering_actor_changes_are_rechecked_before_writes(self):
        self.stages()
        self.api.source["merge_commit_sha"] = self.target
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.api.source["merge_commit_sha"] = self.source
        self.api.actor = 12
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.assertFalse(self.api.pulls)

    def test_duplicate_and_spoofed_tracking_issues_block(self):
        self.stages("track")
        self.api.issues.append(copy.deepcopy(self.api.issues[0]))
        with self.assertRaises(c.Failure):
            self.executor.track()
        self.api.issues.pop()
        self.api.issues[0]["user"]["id"] = 123
        with self.assertRaises(c.Failure):
            self.executor.track()

    def test_issue_pagination_ignores_same_title_without_marker(self):
        self.stages("track")
        real = self.api.issues.pop()
        self.api.issues = [{"number": i + 200, "title": real["title"], "body": "",
                            "user": {"id": 12}} for i in range(100)] + [real]
        self.assertEqual(self.executor.track()["issue_number"], 101)
        self.assertTrue(any("page=2" in path for _, path, _ in self.api.calls))

    def test_closed_issue_requires_verified_merged_pr(self):
        self.stages()
        self.api.issues[0]["state"] = "closed"
        with self.assertRaises(c.Failure):
            self.executor.track()
        self.api.issues[0]["state"] = "open"
        self.executor.publish()
        self.api.issues[0]["state"] = "closed"
        self.api.pulls[0].update(state="closed", merged=True, merged_at="2026-09-14T00:00:00Z")
        self.assertEqual(self.executor.track()["issue_number"], 101)

    def test_ambiguous_issue_create_is_not_retried_in_same_run(self):
        self.executor.validate()
        route = "/repos/" + self.env["GITHUB_REPOSITORY"] + "/issues"
        self.api.fail_post = route
        for _ in range(2):
            with self.assertRaises(c.Failure):
                self.executor.track()
        self.assertEqual(sum(method == "POST" for method, _, _ in self.api.calls), 1)
        self.assertTrue((self.config.state_dir / "tracking.json").exists())

    def test_lost_create_response_can_reconcile_without_reposting(self):
        self.executor.validate()
        self.api.lose_post_response = "/repos/" + self.env["GITHUB_REPOSITORY"] + "/issues"
        with self.assertRaises(c.Failure):
            self.executor.track()
        self.assertEqual(self.executor.track()["issue_number"], 101)
        self.assertEqual(len(self.api.issues), 1)

    def test_lost_issue_response_with_stale_listing_blocks_new_attempt_and_run(self):
        route = self.executor.root + "/issues"
        self.executor.validate()
        self.api.lose_post_response = route
        with self.assertRaisesRegex(c.Failure, "^api_write_ambiguous$"):
            self.executor.track()
        self.api.lose_post_response = None
        for run_id, attempt in (("123", "2"), ("124", "1")):
            with self.subTest(run_id=run_id, attempt=attempt):
                self.fresh_attempt(run_id, attempt)
                self.assertFalse((self.config.state_dir / "tracking.json").exists())
                self.executor.validate()
                self.api.stale_paths.add(route)
                with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                    self.executor.track()
                self.api.stale_paths.clear()
                self.assertEqual(self.executor.track()["issue_number"], 101)
        self.assertEqual(sum(method == "POST" for method, _, _ in self.api.calls), 1)
        self.assertEqual(len(self.api.issues), 1)

    def test_lost_source_comment_response_stale_on_rerun_never_reposts(self):
        self.stages()
        route = self.executor.root + "/issues/7/comments"
        self.api.lose_post_response = route
        with self.assertRaisesRegex(c.Failure, "^api_write_ambiguous$"):
            self.executor.publish()
        self.api.lose_post_response = None
        creates = sum(method == "POST" for method, _, _ in self.api.calls)
        head = git(self.origin, "rev-parse", self.executor.branch)
        for run_id, attempt in (("123", "2"), ("124", "1")):
            with self.subTest(run_id=run_id, attempt=attempt):
                self.fresh_attempt(run_id, attempt)
                self.assertFalse((self.config.state_dir / "publication.json").exists())
                self.stages()
                self.api.stale_paths.add(route)
                with patch.object(c.GitRepo, "push") as push:
                    with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                        self.executor.publish()
                    self.api.stale_paths.clear()
                    self.assertEqual(self.executor.publish()["status"], "pr-reused")
                    push.assert_not_called()
                self.assertEqual(sum(method == "POST" for method, _, _ in self.api.calls), creates)
                self.assertEqual(git(self.origin, "rev-parse", self.executor.branch), head)
        self.assertTrue(any(method == "PATCH" for method, _, _ in self.api.calls))
        self.assertEqual([len(x) for x in self.api.comments.values()], [1, 1])

    def test_incomplete_feedback_does_not_guess_recovery_on_new_attempt(self):
        self.stages()
        route = self.executor.root + "/issues/101/comments"
        self.api.lose_post_response = route
        with self.assertRaisesRegex(c.Failure, "^api_write_ambiguous$"):
            self.executor.publish()
        self.api.lose_post_response = None
        creates = sum(method == "POST" for method, _, _ in self.api.calls)
        self.fresh_attempt()
        self.stages()
        # First hide the ambiguous comment, then expose it. Neither a stale
        # listing nor a proven Issue/PR permits creating the missing source comment.
        for stale in (True, False):
            with self.subTest(stale=stale):
                self.api.stale_paths = {route} if stale else set()
                with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                    self.executor.publish()
        self.assertEqual(sum(method == "POST" for method, _, _ in self.api.calls), creates)
        self.assertEqual(len(self.api.comments[101]), 1)
        self.assertNotIn(7, self.api.comments)

    def test_ambiguous_push_cannot_be_retried_without_branch_on_new_run(self):
        self.stages()
        with patch.object(c.GitRepo, "push", side_effect=c.Failure("push_failed_or_ambiguous")) as push:
            with self.assertRaisesRegex(c.Failure, "^push_failed_or_ambiguous$"):
                self.executor.publish()
            push.assert_called_once()
        self.fresh_attempt("124", "1")
        self.stages()
        with patch.object(c.GitRepo, "push") as push:
            with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                self.executor.publish()
            push.assert_not_called()
        self.assertFalse(self.api.pulls)
        self.assertEqual(git(self.origin, "branch", "--list", "backport/*"), "")

    def test_lost_pr_response_with_stale_listing_cannot_create_on_new_run(self):
        self.stages()
        route = self.executor.root + "/pulls"
        self.api.lose_post_response = route
        with self.assertRaisesRegex(c.Failure, "^api_write_ambiguous$"):
            self.executor.publish()
        self.api.lose_post_response = None
        self.api.stale_paths.add(route)
        head = git(self.origin, "rev-parse", self.executor.branch)
        self.fresh_attempt("124", "1")
        self.stages()
        with patch.object(c.GitRepo, "push") as push:
            with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                self.executor.publish()
            push.assert_not_called()
        self.assertEqual(sum(method == "POST" and path == route for method, path, _ in self.api.calls), 1)
        self.assertEqual(len(self.api.pulls), 1)
        self.assertEqual(git(self.origin, "rev-parse", self.executor.branch), head)

    def test_known_dry_runs_and_other_sources_allow_fresh_creation(self):
        self.api.runs.extend([self.api.workflow_run(120, dry_run=True, attempt=2),
                              self.api.workflow_run(121, source_pr=8)])
        self.assertEqual(self.stages("publish")["status"], "pr-created")
        self.assertEqual(sum(path == self.executor.root + "/actions/runs/123"
                             for _, path, _ in self.api.calls), 5)

    def test_history_gate_blocks_any_previous_nondry_conclusion(self):
        self.executor.validate()
        previous = self.api.workflow_run(122)
        self.api.runs.append(previous)
        for conclusion in (None, "success", "failure", "cancelled", "skipped", "timed_out"):
            with self.subTest(conclusion=conclusion):
                previous.update(conclusion=conclusion)
                with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                    self.executor.track()
        self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))

    def test_history_read_failure_blocks_creation_without_local_ambiguity(self):
        self.executor.validate()
        original = self.api.request
        for suffix in ("/actions/runs/123", "/actions/workflows/backport-demo.yml/runs"):
            def fail_history(method, path, data=None):
                if path.partition("?")[0] == self.executor.root + suffix:
                    raise c.Failure("api_read_failed")
                return original(method, path, data)
            with self.subTest(suffix=suffix), patch.object(self.api, "request", side_effect=fail_history):
                with self.assertRaisesRegex(c.Failure, "^api_read_failed$"):
                    self.executor.track()
                self.assertFalse((self.config.state_dir / "tracking.json").exists())
        self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))

    def test_current_run_must_match_repository_workflow_source_and_attempt(self):
        original = self.api.request
        mutations = [("id", 999), ("workflow_id", True), ("run_attempt", 2),
                     ("repository", {"id": 1, "full_name": c.REPOSITORY}),
                     ("head_repository", {"id": c.REPOSITORY_ID, "full_name": "evil/repo"}),
                     ("path", ".github/workflows/other.yml"), ("event", "pull_request"),
                     ("head_branch", "feature"), ("display_title", None),
                     ("display_title", "Backport PR 8 to 29.x (dry run = false)"),
                     ("display_title", "Backport PR 7 to 29.x (dry run = true)")]
        for key, value in mutations:
            def changed_run(method, path, data=None):
                result = original(method, path, data)
                if path == self.executor.root + "/actions/runs/123":
                    result[key] = value
                return result
            with self.subTest(key=key, value=value), patch.object(self.api, "request", side_effect=changed_run):
                with self.assertRaises(c.Failure):
                    self.executor.require_fresh_creation()
        self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))

    def test_unknown_or_wrong_scope_history_never_grants_creation(self):
        mutations = [("id", "122"), ("workflow_id", 999), ("run_attempt", 0),
                     ("repository", {"id": 1, "full_name": c.REPOSITORY}),
                     ("head_repository", None), ("event", "push"), ("head_branch", "feature"),
                     ("path", ".github/workflows/other.yml"), ("display_title", None),
                     ("display_title", "old workflow title"),
                     ("display_title", "Backport PR 07 to 29.x (dry run = true)"),
                     ("display_title", "Backport PR 7 to 29.x (dry run = true)\n"),
                     ("display_title", "Backport PR 2147483648 to 29.x (dry run = true)")]
        current = self.api.runs[0]
        for key, value in mutations:
            previous = self.api.workflow_run(122, dry_run=True)
            previous[key] = value
            self.api.runs = [current, previous]
            with self.subTest(key=key, value=value), self.assertRaises(c.Failure):
                self.executor.require_fresh_creation()

    def test_history_paginates_all_runs_including_current_and_possible_writer(self):
        current = self.api.runs[0]
        dry_runs = [self.api.workflow_run(i, dry_run=True) for i in range(1000, 1100)]
        self.api.runs = dry_runs + [current]
        self.executor.require_fresh_creation()
        self.assertTrue(any(path.endswith("per_page=100&page=2") for _, path, _ in self.api.calls))
        self.api.runs.append(self.api.workflow_run(122))
        with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
            self.executor.require_fresh_creation()

    def test_history_rejects_incomplete_duplicate_missing_current_and_oversize_pages(self):
        current = self.api.runs[0]
        dry = self.api.workflow_run(122, dry_run=True)
        pages = [[], {}, {"total_count": True, "workflow_runs": [current]},
                 {"total_count": 1, "workflow_runs": {}},
                 {"total_count": 0, "workflow_runs": []},
                 {"total_count": 1, "workflow_runs": [dry]},
                 {"total_count": 2, "workflow_runs": [current]},
                 {"total_count": 2, "workflow_runs": [current, current]},
                 {"total_count": 1, "workflow_runs": [{**current, "run_attempt": 2}]},
                 {"total_count": 1, "workflow_runs": [{**current, "display_title": dry["display_title"]}]},
                 {"total_count": 101, "workflow_runs": [dry] * 101},
                 {"total_count": 100001, "workflow_runs": [current]}]
        original = self.api.request
        for page in pages:
            def broken_page(method, path, data=None):
                result = original(method, path, data)
                return page if "/actions/workflows/" in path else result
            with self.subTest(page=page), patch.object(self.api, "request", side_effect=broken_page):
                with self.assertRaises(c.Failure):
                    self.executor.require_fresh_creation()

    def test_history_detects_count_change_and_repeated_page(self):
        self.api.runs.extend(self.api.workflow_run(i, dry_run=True) for i in range(1000, 1100))
        original = self.api.request
        for changed_count in (True, False):
            def unstable_page(method, path, data=None):
                result = original(method, path, data)
                if "/actions/workflows/" in path and path.endswith("page=2"):
                    if changed_count:
                        result["total_count"] += 1
                    else:
                        result["workflow_runs"] = [self.api.runs[0]]
                return result
            with self.subTest(changed_count=changed_count), patch.object(self.api, "request", side_effect=unstable_page):
                with self.assertRaisesRegex(c.Failure, "^(run_history_changed|duplicate_run_history)$"):
                    self.executor.require_fresh_creation()

    def test_rerun_attempt_blocks_creation_even_without_older_run_entries(self):
        self.fresh_attempt()
        self.executor.validate()
        with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
            self.executor.track()
        self.assertEqual(len(self.api.runs), 1)
        self.assertFalse(self.api.issues)

    def test_dry_rerun_does_not_need_history_or_mutate(self):
        self.env["INPUT_DRY_RUN"] = "true"
        self.fresh_attempt()
        with patch.object(self.executor, "require_fresh_creation", side_effect=AssertionError("unneeded history")), \
                patch.object(c.GitRepo, "push", side_effect=AssertionError("dry push")):
            self.assertEqual(self.stages("publish")["status"], "dry-run")
        self.assertTrue(all(method == "GET" and "/actions/" not in path for method, path, _ in self.api.calls))

    def test_history_is_rechecked_before_branch_push(self):
        self.stages()
        self.api.runs.append(self.api.workflow_run(122))
        with patch.object(c.GitRepo, "push") as push:
            with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                self.executor.publish()
            push.assert_not_called()
        self.assertFalse(self.api.pulls)

    def test_history_is_rechecked_after_push_before_pr_creation(self):
        self.stages()
        original = c.GitRepo.push
        def push_then_history(repo, branch):
            original(repo, branch)
            self.api.runs.append(self.api.workflow_run(122))
        with patch.object(c.GitRepo, "push", new=push_then_history):
            with self.assertRaisesRegex(c.Failure, "^previous_run_may_have_written$"):
                self.executor.publish()
        self.assertTrue(git(self.origin, "branch", "--list", "backport/*"))
        self.assertFalse(self.api.pulls)
        self.assertEqual(sum(method == "POST" for method, _, _ in self.api.calls), 1)

    def test_push_lease_rejects_racing_fast_forward_target_without_changes(self):
        self.stages()
        branch = self.executor.branch
        original = c.GitRepo.push
        def racing_push(repo, name):
            self.assertEqual(name, branch)
            self.assertIsNone(repo.branch_head(name))
            # A plain push would fast-forward this competing branch to HEAD.
            git(self.origin, "branch", name, self.target)
            self.assertTrue(repo.ancestor(self.target, "HEAD"))
            with patch.object(repo, "command", wraps=repo.command) as command:
                try:
                    original(repo, name)
                finally:
                    args, kwargs = command.call_args
                    self.assertIn("--force-with-lease=refs/heads/" + name + ":", args[0])
                    self.assertTrue(kwargs["auth"])
        before = git(self.origin, "show-ref")
        with patch.object(c.GitRepo, "push", new=racing_push):
            with self.assertRaisesRegex(c.Failure, "^push_failed_or_ambiguous$"):
                self.executor.publish()
        self.assertEqual(git(self.origin, "rev-parse", branch), self.target)
        after = git(self.origin, "show-ref").splitlines()
        self.assertEqual(sorted(after), sorted(before.splitlines() + [self.target + " refs/heads/" + branch]))
        self.assertFalse(self.api.pulls)
        self.assertFalse(self.api.comments)

    def test_mismatched_existing_branch_and_closed_pr_block(self):
        self.stages()
        git(self.origin, "branch", "backport/29.x/pr-7", self.target)
        with self.assertRaises(c.Failure):
            self.executor.publish()
        git(self.origin, "branch", "-D", "backport/29.x/pr-7")
        self.executor.publish()
        self.api.pulls[0].update(state="closed", merged=False)
        with self.assertRaises(c.Failure):
            self.executor.publish()

    def test_github_output_and_summary_are_fixed_and_single_line(self):
        self.env.update(GITHUB_OUTPUT=str(self.root / "output"),
                        GITHUB_STEP_SUMMARY=str(self.root / "summary"), INPUT_DRY_RUN="true")
        self.configure()
        self.api.source.update(title="AB#999\n<script>untrusted title</script>", body="untrusted body")
        for stage in ("validate", "track", "prepare", "publish"):
            with self.subTest(stage=stage):
                (self.root / "summary").write_bytes(b"")
                getattr(self.executor, stage)()
                summary = (self.root / "summary").read_text()
                for value in ("Source SHA: " + self.source, "Target base SHA: " + self.target,
                              "Target: releases/29.x", "Branch: backport/29.x/pr-7", "Files (1):",
                              "src/one.al", "https://github.com/" + c.REPOSITORY + "/pull/7",
                              "Dry run: true", "No remote changes."):
                    self.assertIn(value, summary)
                for unsafe in ("offline-fixture", "AB#", "untrusted", "<script>"):
                    self.assertNotIn(unsafe, summary)
        output = (self.root / "output").read_text()
        self.assertIn("plan_ready=true\n", output)
        self.assertIn("status=dry-run\n", output)
        self.assertNotIn("offline-fixture", output)

    def test_summary_keeps_markdown_filenames_in_escaped_literal_block(self):
        plan = self.executor.validate()
        path = "src/[link](https&colon;evil)`&lt;script&gt;.al"
        plan["files"] = [c.validate_path(path)]
        self.env["GITHUB_STEP_SUMMARY"] = str(self.root / "summary")
        self.configure()
        self.executor.summary("validated", plan)
        summary = (self.root / "summary").read_text()
        self.assertIn("<pre>\nsrc/[link](https&amp;colon;evil)`&amp;lt;script&amp;gt;.al\n</pre>", summary)
        self.assertNotIn("&lt;script&gt;", summary)

    def test_summary_rejects_invalid_plan_fields_without_writing(self):
        plan = self.executor.validate()
        self.env["GITHUB_STEP_SUMMARY"] = str(self.root / "summary")
        self.configure()
        for key, value in (("source_sha", "a" * 40 + "\nSECRET"),
                           ("target_base_sha", "<script>"), ("target_ref", "other\nSECRET"),
                           ("files", ["src/a.al\nSECRET"]), ("files", [])):
            with self.subTest(key=key, value=value), self.assertRaises(c.Failure):
                self.executor.summary("validated", {**plan, key: value})
        self.assertFalse((self.root / "summary").exists())
        self.executor.summary("needs-attention")
        self.assertNotIn("SECRET", (self.root / "summary").read_text())

    def test_added_and_deleted_files_are_supported(self):
        git(self.origin, "switch", "feature")
        (self.origin / "src/one.al").unlink()
        (self.origin / "src/new.al").write_bytes(b"new AL source\n")
        git(self.origin, "add", "-A")
        git(self.origin, "commit", "-m", "replace file")
        head = git(self.origin, "rev-parse", "HEAD")
        git(self.origin, "update-ref", "refs/pull/7/head", head)
        git(self.origin, "switch", "main")
        git(self.origin, "reset", "--hard", self.target)
        git(self.origin, "merge", "--squash", "feature")
        git(self.origin, "commit", "-m", "squash")
        self.api.source.update(merge_commit_sha=git(self.origin, "rev-parse", "HEAD"), changed_files=2)
        self.api.source["head"]["sha"] = head
        self.api.commits = [{"sha": value} for value in git(
            self.origin, "rev-list", "--reverse", self.target + ".." + head).splitlines()]
        self.assertEqual(self.stages("publish")["status"], "pr-created")
        self.assertEqual(git(self.origin, "ls-tree", "--name-only", "backport/29.x/pr-7", "src/one.al"), "")
        self.assertEqual(git(self.origin, "show", "backport/29.x/pr-7:src/new.al"), "new AL source")

    def test_merge_commit_with_two_parents_is_rejected(self):
        git(self.origin, "reset", "--hard", self.target)
        git(self.origin, "merge", "--no-ff", "feature", "-m", "merge commit")
        self.api.source["merge_commit_sha"] = git(self.origin, "rev-parse", "HEAD")
        with self.assertRaises(c.Failure):
            self.executor.validate()

    def test_ambiguous_pr_create_is_not_retried(self):
        self.stages()
        route = "/repos/" + self.env["GITHUB_REPOSITORY"] + "/pulls"
        self.api.fail_post = route
        for _ in range(2):
            with self.assertRaises(c.Failure):
                self.executor.publish()
        self.assertEqual(sum(method == "POST" and path == route for method, path, _ in self.api.calls), 1)
        self.assertTrue((self.config.state_dir / "publication.json").exists())

    def test_lost_pr_create_response_reuses_verified_pr(self):
        self.stages()
        self.api.lose_post_response = "/repos/" + self.env["GITHUB_REPOSITORY"] + "/pulls"
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.assertEqual(self.executor.publish()["status"], "pr-reused")
        self.assertEqual(len(self.api.pulls), 1)

    def test_ambiguous_comment_create_cannot_retry_when_pr_status_changes(self):
        self.stages()
        route = "/repos/" + self.env["GITHUB_REPOSITORY"] + "/issues/101/comments"
        self.api.fail_post = route
        for _ in range(2):
            with self.assertRaises(c.Failure):
                self.executor.publish()
        self.assertEqual(sum(method == "POST" and path == route for method, path, _ in self.api.calls), 1)

    def test_successful_write_with_wrong_readback_is_rejected(self):
        self.stages()
        self.executor.publish()
        self.api.pulls[0]["head"]["sha"] = self.target
        with self.assertRaises(c.Failure):
            self.executor.publish()

    def test_api_transport_blocks_dry_writes_before_opening_connection(self):
        cfg = c.Config.from_env({**self.env, "INPUT_DRY_RUN": "true"})
        api = c.GitHub(cfg)
        with self.assertRaises(c.Failure):
            api.request("POST", "/repos/" + self.env["GITHUB_REPOSITORY"] + "/issues", {})

    def test_git_credentials_are_scoped_in_environment_only(self):
        inherited = {"GH_TOKEN": "ambient-gh-token", "GITHUB_TOKEN": "ambient-github-token",
                     "GIT_CONFIG_COUNT": "1", "GIT_CONFIG_KEY_0": "remote.origin.url",
                     "GIT_CONFIG_VALUE_0": "https://example.invalid/unwanted.git"}
        with patch.dict(os.environ, inherited), c.GitRepo(self.config) as repo:
            self.assertTrue(all(key not in repo.env for key in inherited))
            with patch("controller.subprocess.run") as run:
                repo.command(("push", repo.origin, "HEAD:refs/heads/backport/29.x/pr-7"), auth=True)
                args, kwargs = run.call_args
                self.assertNotIn(self.config.token, str(args))
                self.assertNotIn("GH_TOKEN", kwargs["env"])
                self.assertNotIn("GITHUB_TOKEN", kwargs["env"])
                self.assertEqual(kwargs["env"]["GIT_CONFIG_KEY_0"],
                                 "http.https://github.com/AleksanderGladkov/BCApps-Backport-Test.git.extraHeader")
                self.assertTrue(kwargs["env"]["GIT_CONFIG_VALUE_0"].startswith("Authorization: Basic "))
            self.assertNotIn(self.config.token, (repo.path / ".git/config").read_text())

    def test_feedback_contains_reason_and_never_copies_source_text(self):
        git(self.origin, "switch", "releases/29.x")
        (self.origin / "src/one.al").write_bytes(b"RELEASE\n")
        git(self.origin, "commit", "-am", "conflict")
        self.api.target = git(self.origin, "rev-parse", "HEAD")
        git(self.origin, "switch", "main")
        self.api.source.update(title="AB#999\nmalicious title", body="arbitrary body")
        self.stages("publish")
        for items in self.api.comments.values():
            self.assertIn("cherry_pick_conflict", items[0]["body"])
            self.assertNotIn("AB#", items[0]["body"])

    def test_new_attempt_reconciles_existing_issue_from_old_artifact(self):
        self.stages("track")
        self.env["GITHUB_RUN_ATTEMPT"] = "2"
        self.configure()
        # New validation creates a new binding; never consume the old plan.
        (self.config.state_dir / "plan.json").unlink()
        self.executor.validate()
        self.assertEqual(self.executor.track()["issue_number"], 101)

    def test_run_scoped_ambiguity_cannot_be_erased_by_prepare(self):
        self.stages()
        route = "/repos/" + self.env["GITHUB_REPOSITORY"] + "/pulls"
        self.api.fail_post = route
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.executor.prepare()
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.assertEqual(sum(method == "POST" and path == route for method, path, _ in self.api.calls), 1)

    def test_forged_patch_with_matching_artifact_digest_is_still_rejected(self):
        self.stages()
        forged = b"untrusted replacement content"
        (self.config.state_dir / "patch.bin").write_bytes(forged)
        self.alter_json("result.json", lambda x: x.update(patch_sha256=hashlib.sha256(forged).hexdigest()))
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.assertFalse(self.api.pulls)
        self.assertEqual(git(self.origin, "branch", "--list", "backport/*"), "")

    def test_plan_file_list_cannot_be_expanded_even_with_matching_hashes(self):
        self.stages()
        self.alter_json("plan.json", lambda x: x["files"].append("src/evil.al"))
        plan = json.loads((self.config.state_dir / "plan.json").read_bytes())
        plan_hash = c.digest(c.encoded(plan))
        for name in ("tracking.json", "result.json"):
            self.alter_json(name, lambda x: x.update(plan_hash=plan_hash))
        with self.assertRaises(c.Failure):
            self.executor.publish()
        self.assertFalse(self.api.pulls)

    def test_missing_target_branch_and_wrong_api_repository_fail_readonly(self):
        original = self.api.request
        def missing_branch(method, path, data=None):
            if "/branches/" in path:
                raise c.Failure("api_read_failed")
            return original(method, path, data)
        with patch.object(self.api, "request", side_effect=missing_branch), self.assertRaises(c.Failure):
            self.executor.validate()
        self.api.repo["id"] = 1
        with self.assertRaises(c.Failure):
            self.executor.validate()
        self.assertTrue(all(method == "GET" for method, _, _ in self.api.calls))

    def test_cli_rejects_inputs_without_echoing_untrusted_values(self):
        import contextlib
        import io
        output = io.StringIO()
        with patch.dict(os.environ, {**self.env, "INPUT_SOURCE_PR": "7\nSECRET"}, clear=True), contextlib.redirect_stderr(output):
            self.assertEqual(c.main(["validate"]), 1)
        self.assertNotIn("SECRET", output.getvalue())
        self.assertIn("invalid_number", output.getvalue())


if __name__ == "__main__":
    unittest.main()